# Generated by Django 3.2.13 on 2022-05-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220510_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Abbreviation')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measurement'),
        ),
        migrations.AlterField(
            model_name='masterpartnumber',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measurement'),
        ),
        migrations.AlterField(
            model_name='noninventory',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measurement'),
        ),
        migrations.AlterField(
            model_name='service',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measurement'),
        ),
    ]
