# Generated by Django 3.2.13 on 2022-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='workorder',
            field=models.CharField(max_length=100, unique=True, verbose_name='Workorder'),
        ),
    ]
