# Generated by Django 3.2.13 on 2022-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auto_20220524_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderservice',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custom Rate'),
        ),
    ]
