# Generated by Django 3.2.13 on 2022-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_auto_20220527_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinventoryproduct',
            name='custom_measurement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Measurement'),
        ),
        migrations.AddField(
            model_name='workorderinventoryproduct',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custom Rate'),
        ),
        migrations.AddField(
            model_name='workorderinventoryproduct',
            name='measurement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement'),
        ),
    ]
