# Generated by Django 3.2.13 on 2022-08-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_workorderinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinvoice',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
